swagger: "2.0"
info:
  version: 1.0.0
  title: Gym Badges API

tags:
  - name: Login
    description: Endpoints responsible for login operations.

paths:

  /login:
    post:
      operationId: login
      tags:
        - Login
      produces:
        - application/json
      parameters:
        - name: input
          description: Data required for login
          in: body
          required: true
          schema:
            $ref: "#/definitions/login_request_body"
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/login_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  /login-with-token:
    get:
      operationId: loginWithToken
      tags:
        - LoginWithToken
      produces:
        - application/json
      parameters:
        - name: auth_user_id
          in: header
          required: true
          type: string
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object


  /user/{user_id}:
    get:
      operationId: getUserInfo
      summary: Find user by ID
      tags:
        - User
      produces:
        - application/json
      parameters:
        - name: user_id  # User's id you want to get.
          in: path
          description: Username
          required: true
          type: string
        - name: auth_user_id  # Your own user id. For authentication.
          in: header
          required: true
          type: string
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/get_user_info_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        404:
          description: Not Found Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the not found error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  /user:
    post:
      operationId: createUser
      summary: Create user
      tags:
        - User
      produces:
        - application/json
      parameters:
        - name: input
          description: Data required for login
          in: body
          required: true
          schema:
            $ref: "#/definitions/create_user_request"
      responses:
        201:
          description: Success Response
          schema:
            $ref: "#/definitions/login_response"
        409:
          description: Conflict Error
          schema:
            $ref: "#/definitions/generic_response"
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  # -----------------------------------------------------
  # STATS
  # -----------------------------------------------------

  /stats/weight/{user_id}:
    get:
      operationId: getWeightHistoryByUserID
      summary: Get weight history by user_id
      tags:
        - Stats
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: User's id you want to get.
          required: true
          type: string
        - name: auth_user_id
          in: header
          description: Your own user id. For authentication.
          required: true
          type: string
        - name: months
          in: query
          description: Number of months to be consulted. To return all use 0
          required: true
          type: integer
          format: int32
          enum:
            - 0
            - 3
            - 6
            - 12
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/measurement_history_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        404:
          description: Not Found Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the not found error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  /stats/streak/{user_id}:
    get:
      operationId: getStreakCalendarByUserID
      summary: Get streak calendar by user_id
      tags:
        - Stats
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: User's id you want to get.
          required: true
          type: string
        - name: auth_user_id
          in: header
          description: Your own user id. For authentication.
          required: true
          type: string
        - name: month
          in: query
          description: Month to be consulted.
          required: true
          type: integer
          format: int32
        - name: year
          in: query
          description: Year to be consulted.
          required: true
          type: integer
          format: int32
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/streak_calendar_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        404:
          description: Not Found Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the not found error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  /stats/fat/{user_id}:
    get:
      operationId: getFatHistoryByUserID
      summary: Get fat history by user_id
      tags:
        - Stats
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: User's id you want to get.
          required: true
          type: string
        - name: auth_user_id
          in: header
          description: Your own user id. For authentication.
          required: true
          type: string
        - name: months
          in: query
          description: Number of months to be consulted. To return all use 0
          required: true
          type: integer
          format: int32
          enum:
            - 0
            - 3
            - 6
            - 12
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/measurement_history_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        404:
          description: Not Found Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the not found error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  # -----------------------------------------------------
  # FRIENDS
  # -----------------------------------------------------

  /friends/{user_id}:
    get:
      operationId: getFriendsByUserID
      summary: Get friends info by user_id
      tags:
        - Friends
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: User's id you want to get.
          required: true
          type: string
        - name: auth_user_id
          in: header
          description: Your own user id. For authentication.
          required: true
          type: string
        - name: page
          in: query
          description: Friends list pagination.
          required: true
          type: integer
          format: int32
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/friends_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        404:
          description: Not Found Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the not found error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  # -----------------------------------------------------
  # BADGES
  # -----------------------------------------------------

  /badges/{user_id}:
    get:
      operationId: getBadgesByUserID
      summary: Get badges info by user_id
      tags:
        - Badges
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: User's id you want to get.
          required: true
          type: string
        - name: auth_user_id
          in: header
          description: Your own user id. For authentication.
          required: true
          type: string
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/badges_by_user_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        404:
          description: Not Found Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the not found error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

securityDefinitions:

  jwt:
    type: apiKey
    in: header
    name: token

definitions:

  generic_response:
    type: object
    title: Generic Operation Response
    description: Describes the generic result of a request.
    properties:
      code:
        type: string
      message:
        type: string

  login_request_body:
    type: object
    title: Login Response
    description: Describes the login response with the information necessary to maintain the session.
    properties:
      user_id:
        type: string
      password:
        type: string

  login_response:
    type: object
    title: Login Response
    description: Describes the login response with the information necessary to maintain the session.
    properties:
      token:
        type: string

  get_user_info_response:
    type: object
    title: User info response
    properties:
      user_id:
        type: string
        x-omitempty: false
      body_fat:
        type: number
        format: float
        x-omitempty: false
      current_week:
        type: array
        items:
          type: boolean
        x-omitempty: false
      experience:
        type: integer
        format: int64
        x-omitempty: false
      image:
        type: string  # url
        x-omitempty: false
      name:
        type: string
        x-omitempty: false
      streak:
        type: integer
        format: int32
        x-omitempty: false
      weight:
        type: number
        format: float
        x-omitempty: false

  measurement_history_response:
    type: object
    title: Measurement history response
    properties:
      days:
        type: array
        items:
          $ref: "#/definitions/measurement_per_day"

  measurement_per_day:
    type: object
    title: Measurement pre day info
    properties:
      date:
        type: string
        x-omitempty: false
      value:
        type: number
        format: float
        x-omitempty: false

  streak_calendar_response:
    type: object
    title: Streak calendar response
    properties:
      streak:
        type: number
        format: int32
        x-omitempty: false
      weekly_goal:
        type: number
        format: int32
        x-omitempty: false
      days:
        type: array
        items:
          type: string

  friends_response:
    type: object
    title: Friends information list
    properties:
      friends:
        type: array
        items:
          $ref: "#/definitions/friend_info"

  friend_info:
    type: object
    title: Friends information list
    properties:
      name:
        type: string
        x-omitempty: false
      user:
        type: string
        x-omitempty: false
      image:
        type: string
        x-omitempty: false
      level:
        type: number
        format: int32
        x-omitempty: false
      streak:
        type: number
        format: int32
        x-omitempty: false
      weight:
        type: number
        format: float
        x-omitempty: false
      fat:
        type: number
        format: float
        x-omitempty: false
      top_feats:
        type: array
        items:
          $ref: "#/definitions/feat"

  feat:
    type: object
    title: Create user request
    properties:
      name:
        type: string
        x-omitempty: false
      description:
        type: string
        x-omitempty: false
      image:
        type: string
        x-omitempty: false

  create_user_request:
    type: object
    title: Create user request
    properties:
      email:
        type: string
      image:
        type: string
      name:
        type: string
      password:
        type: string
      user_id:
        type: string

  badges_by_user_response:
    title: User badge list response
    type: array
    items:
      $ref: "#/definitions/badge"

  badge:
    type: object
    title: User badge
    properties:
      achieved:
        type: boolean
      description:
        type: string
      id:
        type: string
      image:
        type: string
      name:
        type: string
      children:
        type: array
        items:
          $ref: "#/definitions/badge"
