swagger: "2.0"
info:
  version: 1.0.0
  title: Gym Badges API

tags:
  - name: Login
    description: Endpoints responsible for login operations.

paths:

  /login:
    post:
      operationId: login
      tags:
        - Login
      produces:
        - application/json
      parameters:
        - name: input
          description: Data required for login
          in: body
          required: true
          schema:
            $ref: "#/definitions/login_request_body"
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/login_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

  /login-with-token:
    get:
      operationId: loginWithToken
      tags:
        - LoginWithToken
      produces:
        - application/json
      parameters:
        - name: user_id
          in: header
          required: true
          type: string
      security:
        - jwt: [ ]
      responses:
        200:
          description: Success Response
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
          

  /user/{user_id}:
    get:
      operationId: getUserInfo
      summary: Find user by ID
      tags:
        - User
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: Username
          required: true
          type: string
        - name: token
          in: header
          description: Session authentication token
          required: true
          type: string
      responses:
        200:
          description: Success Response
          schema:
            $ref: "#/definitions/get_user_info_response"
        401:
          description: Unauthorized Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the unauthorized error response object
        500:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/generic_response"
            description: Contains the operation error response object

securityDefinitions:

  jwt:
    type: apiKey
    in: header
    name: token

definitions:

  generic_response:
    type: object
    title: Generic Operation Response
    description: Describes the generic result of a request.
    properties:
      code:
        type: string
      message:
        type: string

  login_request_body:
    type: object
    title: Login Response
    description: Describes the login response with the information necessary to maintain the session.
    properties:
      user_id:
        type: string
      password:
        type: string

  login_response:
    type: object
    title: Login Response
    description: Describes the login response with the information necessary to maintain the session.
    properties:
      token:
        type: string

  get_user_info_response:
    type: object
    title: User info response
    properties:
      image:
        type: string
        format: byte
      experience:
        type: integer
        format: int64
      streak:
        type: integer
        format: int32
      weight:
        type: number
        format: float
      body_fat:
        type: number
        format: float
      current_week:
        type: array
        items:
          type: boolean
