INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (-1, 'chest', '', '', null, 0);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (1, 'Do five push-ups', '', '/image/badge/1.svg', -1, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (2, 'Do ten push-ups', '', '/image/badge/2.svg', 1, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (3, 'Do twenty push-ups', '', '/image/badge/3.svg', 2, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (4, 'Do thirty push-ups', '', '/image/badge/4.svg', 3, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (5, 'Do fifty push-ups', '', '/image/badge/5.svg', 4, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (6, 'Do a hundred push-ups', '', '/image/badge/6.svg', 5, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (7, 'Bench press 20kg for 10 reps', '', '/image/badge/7.svg', 2, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (8, 'Bench press 30kg for 10 reps', '', '/image/badge/8.svg', 7, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (9, 'Bench press 40kg for 10 reps', '', '/image/badge/9.svg', 8, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (10, 'Bench press 60kg for 10 reps', '', '/image/badge/10.svg', 9, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (11, 'Bench press 80kg for 5 reps', '', '/image/badge/11.svg', 10, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (12, 'Bench press 100kg for 5 reps', '', '/image/badge/12.svg', 11, 3013);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (13, 'Bench press 120kg for 5 reps', '', '/image/badge/13.svg', 12, 5105);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (14, 'Do five chest dips', '', '/image/badge/14.svg', 2, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (15, 'Do ten chest dips', '', '/image/badge/15.svg', 14, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (16, 'Do twenty chest dips', '', '/image/badge/16.svg', 15, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (17, 'Do thirty chest dips', '', '/image/badge/17.svg', 16, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (18, 'Do fifty chest dips', '', '/image/badge/18.svg', 17, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (-2, 'arms', '', '', null, 0);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (19, 'Biceps curl 8kg dumbbell', '', '/image/badge/19.svg', -2, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (20, 'Biceps curl 10kg dumbbell', '', '/image/badge/20.svg', 19, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (21, 'Biceps curl 12kg dumbbell', '', '/image/badge/21.svg', 20, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (22, 'Biceps curl 16kg dumbbell', '', '/image/badge/22.svg', 21, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (23, 'Biceps curl 20kg dumbbell', '', '/image/badge/23.svg', 22, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (24, 'Biceps curl 25kg dumbbell', '', '/image/badge/24.svg', 23, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (25, 'Biceps curl 30kg dumbbell', '', '/image/badge/25.svg', 24, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (26, 'Shoulder press with 6kg', '', '/image/badge/26.svg', -2, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (27, 'Shoulder press with 10kg', '', '/image/badge/27.svg', 26, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (28, 'Shoulder press with 14kg', '', '/image/badge/28.svg', 27, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (29, 'Shoulder press with 18kg', '', '/image/badge/29.svg', 28, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (30, 'Shoulder press with 22kg', '', '/image/badge/30.svg', 29, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (31, 'Shoulder press with 26kg', '', '/image/badge/31.svg', 30, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (32, 'Shoulder press with 30kg', '', '/image/badge/32.svg', 31, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (33, 'Lateral raises with 4kg', '', '/image/badge/33.svg', -2, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (34, 'Lateral raises with 8kg', '', '/image/badge/34.svg', 33, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (35, 'Lateral raises with 10kg', '', '/image/badge/35.svg', 34, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (36, 'Lateral raises with 12kg', '', '/image/badge/36.svg', 35, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (37, 'Lateral raises with 14kg', '', '/image/badge/37.svg', 36, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (38, 'Lateral raises with 16kg', '', '/image/badge/38.svg', 37, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (39, 'Lateral raises with 20kg', '', '/image/badge/39.svg', 38, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (-3, 'back', '', '', null, 0);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (40, 'Do five pull-ups', '', '/image/badge/40.svg', -3, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (41, 'Do ten pull-ups', '', '/image/badge/41.svg', 40, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (42, 'Do twenty pull-ups', '', '/image/badge/42.svg', 41, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (43, 'Do thirty pull-ups', '', '/image/badge/43.svg', 42, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (44, 'Lat pull-down with 20kg', '', '/image/badge/44.svg', -3, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (45, 'Lat pull-down with 30kg', '', '/image/badge/45.svg', 44, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (46, 'Lat pull-down with 40kg', '', '/image/badge/46.svg', 45, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (47, 'Lat pull-down with 50kg', '', '/image/badge/47.svg', 46, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (48, 'Lat pull-down with 60kg', '', '/image/badge/48.svg', 47, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (49, 'Lat pull-down with 70kg', '', '/image/badge/49.svg', 48, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (50, 'Lat pull-down with 80kg', '', '/image/badge/50.svg', 49, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (-4, 'legs', '', '', null, 0);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (51, 'Squat 20kg for 10 reps', '', '/image/badge/51.svg', -4, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (52, 'Squat 30kg for 10 reps', '', '/image/badge/52.svg', 51, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (53, 'Squat 40kg for 10 reps', '', '/image/badge/53.svg', 52, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (54, 'Squat 60kg for 10 reps', '', '/image/badge/54.svg', 53, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (55, 'Squat 80kg for 10 reps', '', '/image/badge/55.svg', 54, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (56, 'Squat 100kg for 5 reps', '', '/image/badge/56.svg', 55, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (57, 'Squat 120kg for 5 reps', '', '/image/badge/57.svg', 56, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (58, 'Squat 150kg for 5 reps', '', '/image/badge/58.svg', 57, 3013);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (-5, 'core', '', '', null, 0);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (59, 'Do ten abdominal crunches in a row', '', '/image/badge/59.svg', -5, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (60, 'Do twenty-five abdominal crunches in a row', '', '/image/badge/60.svg', 59, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (61, 'Do fifty abdominal crunches in a row', '', '/image/badge/61.svg', 60, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (62, 'Loaded abdominal crunches with 10kg for 10 reps', '', '/image/badge/62.svg', 60, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (63, 'Loaded abdominal crunches with 20kg for 10 reps', '', '/image/badge/63.svg', 62, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (64, 'Loaded abdominal crunches with 30kg for 10 reps', '', '/image/badge/64.svg', 63, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (65, 'Loaded abdominal crunches with 50kg for 10 reps', '', '/image/badge/65.svg', 64, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (-6, 'consistency', '', '', null, 0);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (66, 'The first week', '', '/image/badge/66.svg', -6, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (67, '4 weeks streak', '', '/image/badge/67.svg', 66, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (68, '10 weeks streak', '', '/image/badge/68.svg', 67, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (69, '20 weeks streak', '', '/image/badge/69.svg', 68, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (70, '50 weeks streak', '', '/image/badge/70.svg', 69, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (71, 'First month', '', '/image/badge/71.svg', 66, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (72, 'Reach 100 gym sessions', '', '/image/badge/72.svg', 71, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (73, 'Reach 200 gym sessions', '', '/image/badge/73.svg', 72, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (74, 'Reach 500 gym sessions', '', '/image/badge/74.svg', 73, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (75, 'Six months', '', '/image/badge/75.svg', 71, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (76, 'First year!', '', '/image/badge/76.svg', 75, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (77, 'Two years', '', '/image/badge/77.svg', 76, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (78, 'Three years', '', '/image/badge/78.svg', 77, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (79, 'Five years', '', '/image/badge/79.svg', 78, 1865);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (-7, 'social', '', '', null, 0);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (80, 'Get to the top 500 at the Global Ranking', '', '/image/badge/80.svg', -7, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (81, 'Get to the top 100 at the Global Ranking', '', '/image/badge/81.svg', 80, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (82, 'Get to the top 50 at the Global Ranking', '', '/image/badge/82.svg', 81, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (83, 'Get to the top 10 at the Global Ranking', '', '/image/badge/83.svg', 82, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (84, 'Get to the top 3 at the Global Ranking', '', '/image/badge/84.svg', 83, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (85, 'Get to the top 1 at the Global Ranking', '', '/image/badge/85.svg', 84, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (86, 'Add your first friend', '', '/image/badge/86.svg', -7, 125);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (87, 'Add five friends', '', '/image/badge/87.svg', 86, 247);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (88, 'Add ten friends', '', '/image/badge/88.svg', 87, 389);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (89, 'Add twenty friends', '', '/image/badge/89.svg', 88, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (90, 'Reach the podium at the Friends Ranking with at least 20 friends', '', '/image/badge/90.svg', 89, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (91, 'Get to the top at the Friends Ranking with at least 20 friends', '', '/image/badge/91.svg', 90, 1213);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (92, 'Reach the podium at the Friends Ranking with at least 10 friends', '', '/image/badge/92.svg', 88, 570);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (93, 'Get to the top at the Friends Ranking with at least 10 friends', '', '/image/badge/93.svg', 92, 823);
INSERT INTO badge (id, name, description, image, parent_badge_id, exp) VALUES (94, 'Get to the top at the Friends Ranking with at least 5 friends', '', '/image/badge/94.svg', 87, 389);