INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (-1, 'chest', '', '/image/badge/-1.svg', null);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (1, 'Do five push-ups', '', '/image/badge/1.svg', -1);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (2, 'Do ten push-ups', '', '/image/badge/2.svg', 1);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (3, 'Do twenty push-ups', '', '/image/badge/3.svg', 2);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (4, 'Do thirty push-ups', '', '/image/badge/4.svg', 3);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (5, 'Do fifty push-ups', '', '/image/badge/5.svg', 4);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (6, 'Do a hundred push-ups', '', '/image/badge/6.svg', 5);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (7, 'Bench press 20kg for 10 reps', '', '/image/badge/7.svg', 2);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (8, 'Bench press 30kg for 10 reps', '', '/image/badge/8.svg', 7);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (9, 'Bench press 40kg for 10 reps', '', '/image/badge/9.svg', 8);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (10, 'Bench press 60kg for 10 reps', '', '/image/badge/10.svg', 9);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (11, 'Bench press 80kg for 5 reps', '', '/image/badge/11.svg', 10);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (12, 'Bench press 100kg for 5 reps', '', '/image/badge/12.svg', 11);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (13, 'Bench press 120kg for 5 reps', '', '/image/badge/13.svg', 12);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (14, 'Do five chest dips', '', '/image/badge/14.svg', 2);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (15, 'Do ten chest dips', '', '/image/badge/15.svg', 14);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (16, 'Do twenty chest dips', '', '/image/badge/16.svg', 15);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (17, 'Do thirty chest dips', '', '/image/badge/17.svg', 16);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (18, 'Do fifty chest dips', '', '/image/badge/18.svg', 17);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (-2, 'arms', '', '/image/badge/-2.svg', null);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (19, 'Biceps curl 8kg dumbbell', '', '/image/badge/19.svg', -2);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (20, 'Biceps curl 10kg dumbbell', '', '/image/badge/20.svg', 19);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (21, 'Biceps curl 12kg dumbbell', '', '/image/badge/21.svg', 20);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (22, 'Biceps curl 16kg dumbbell', '', '/image/badge/22.svg', 21);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (23, 'Biceps curl 20kg dumbbell', '', '/image/badge/23.svg', 22);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (24, 'Biceps curl 25kg dumbbell', '', '/image/badge/24.svg', 23);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (25, 'Biceps curl 30kg dumbbell', '', '/image/badge/25.svg', 24);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (26, 'Shoulder press with 6kg', '', '/image/badge/26.svg', -2);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (27, 'Shoulder press with 10kg', '', '/image/badge/27.svg', 26);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (28, 'Shoulder press with 14kg', '', '/image/badge/28.svg', 27);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (29, 'Shoulder press with 18kg', '', '/image/badge/29.svg', 28);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (30, 'Shoulder press with 22kg', '', '/image/badge/30.svg', 29);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (31, 'Shoulder press with 26kg', '', '/image/badge/31.svg', 30);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (32, 'Shoulder press with 30kg', '', '/image/badge/32.svg', 31);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (33, 'Lateral raises with 4kg', '', '/image/badge/33.svg', -2);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (34, 'Lateral raises with 8kg', '', '/image/badge/34.svg', 33);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (35, 'Lateral raises with 10kg', '', '/image/badge/35.svg', 34);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (36, 'Lateral raises with 12kg', '', '/image/badge/36.svg', 35);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (37, 'Lateral raises with 14kg', '', '/image/badge/37.svg', 36);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (38, 'Lateral raises with 16kg', '', '/image/badge/38.svg', 37);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (39, 'Lateral raises with 20kg', '', '/image/badge/39.svg', 38);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (-3, 'back', '', '/image/badge/-3.svg', null);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (40, 'Do five pull-ups', '', '/image/badge/40.svg', -3);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (41, 'Do ten pull-ups', '', '/image/badge/41.svg', 40);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (42, 'Do twenty pull-ups', '', '/image/badge/42.svg', 41);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (43, 'Do thirty pull-ups', '', '/image/badge/43.svg', 42);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (44, 'Lat pull-down with 20kg', '', '/image/badge/44.svg', -3);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (45, 'Lat pull-down with 30kg', '', '/image/badge/45.svg', 44);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (46, 'Lat pull-down with 40kg', '', '/image/badge/46.svg', 45);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (47, 'Lat pull-down with 50kg', '', '/image/badge/47.svg', 46);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (48, 'Lat pull-down with 60kg', '', '/image/badge/48.svg', 47);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (49, 'Lat pull-down with 70kg', '', '/image/badge/49.svg', 48);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (50, 'Lat pull-down with 80kg', '', '/image/badge/50.svg', 49);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (-4, 'legs', '', '/image/badge/-4.svg', null);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (51, 'Squat 20kg for 10 reps', '', '/image/badge/51.svg', -4);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (52, 'Squat 30kg for 10 reps', '', '/image/badge/52.svg', 51);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (53, 'Squat 40kg for 10 reps', '', '/image/badge/53.svg', 52);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (54, 'Squat 60kg for 10 reps', '', '/image/badge/54.svg', 53);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (55, 'Squat 80kg for 10 reps', '', '/image/badge/55.svg', 54);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (56, 'Squat 100kg for 5 reps', '', '/image/badge/56.svg', 55);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (57, 'Squat 120kg for 5 reps', '', '/image/badge/57.svg', 56);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (58, 'Squat 150kg for 5 reps', '', '/image/badge/58.svg', 57);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (-5, 'core', '', '/image/badge/-5.svg', null);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (59, 'Do ten abdominal crunches in a row', '', '/image/badge/59.svg', -5);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (60, 'Do twenty-five abdominal crunches in a row', '', '/image/badge/60.svg', 59);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (61, 'Do fifty abdominal crunches in a row', '', '/image/badge/61.svg', 60);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (62, 'Loaded abdominal crunches with 10kg for 10 reps', '', '/image/badge/62.svg', 60);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (63, 'Loaded abdominal crunches with 20kg for 10 reps', '', '/image/badge/63.svg', 62);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (64, 'Loaded abdominal crunches with 30kg for 10 reps', '', '/image/badge/64.svg', 63);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (65, 'Loaded abdominal crunches with 50kg for 10 reps', '', '/image/badge/65.svg', 64);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (-6, 'consistency', '', '/image/badge/-6.svg', null);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (66, 'The first week', '', '/image/badge/66.svg', -6);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (67, '4 weeks streak', '', '/image/badge/67.svg', 66);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (68, '10 weeks streak', '', '/image/badge/68.svg', 67);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (69, '20 weeks streak', '', '/image/badge/69.svg', 68);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (70, '50 weeks streak', '', '/image/badge/70.svg', 69);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (71, 'First month', '', '/image/badge/71.svg', 66);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (72, 'Reach 100 gym sessions', '', '/image/badge/72.svg', 71);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (73, 'Reach 200 gym sessions', '', '/image/badge/73.svg', 72);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (74, 'Reach 500 gym sessions', '', '/image/badge/74.svg', 73);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (75, 'Six months', '', '/image/badge/75.svg', 71);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (76, 'First year!', '', '/image/badge/76.svg', 75);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (77, 'Two years', '', '/image/badge/77.svg', 76);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (78, 'Three years', '', '/image/badge/78.svg', 77);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (79, 'Five years', '', '/image/badge/79.svg', 78);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (-7, 'social', '', '/image/badge/-7.svg', null);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (80, 'Get to the top 500 at the Global Ranking', '', '/image/badge/80.svg', -7);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (81, 'Get to the top 100 at the Global Ranking', '', '/image/badge/81.svg', 80);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (82, 'Get to the top 50 at the Global Ranking', '', '/image/badge/82.svg', 81);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (83, 'Get to the top 10 at the Global Ranking', '', '/image/badge/83.svg', 82);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (84, 'Get to the top 3 at the Global Ranking', '', '/image/badge/84.svg', 83);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (85, 'Get to the top 1 at the Global Ranking', '', '/image/badge/85.svg', 84);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (86, 'Add your first friend', '', '/image/badge/86.svg', -7);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (87, 'Add five friends', '', '/image/badge/87.svg', 86);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (88, 'Add ten friends', '', '/image/badge/88.svg', 87);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (89, 'Add twenty friends', '', '/image/badge/89.svg', 88);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (90, 'Reach the podium at the Friends Ranking with at least 20 friends', '', '/image/badge/90.svg', 89);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (91, 'Get to the top at the Friends Ranking with at least 20 friends', '', '/image/badge/91.svg', 90);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (92, 'Reach the podium at the Friends Ranking with at least 10 friends', '', '/image/badge/92.svg', 88);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (93, 'Get to the top at the Friends Ranking with at least 10 friends', '', '/image/badge/93.svg', 92);
INSERT INTO badge (id, name, description, image, parent_badge_id) VALUES (94, 'Get to the top at the Friends Ranking with at least 5 friends', '', '/image/badge/94.svg', 87);